"""add budget models

Revision ID: 0002
Revises: 
Create Date: 2026-01-16 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0002'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_pools',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('tenant_id', sa.String(36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_by', sa.String(36), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_ledger',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('tenant_id', sa.String(36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.String(length=50), nullable=False),
    sa.Column('delta_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=20), nullable=False),
    sa.Column('reference_id', sa.String(36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department_budgets',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('tenant_id', sa.String(36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('budget_pool_id', sa.String(36), nullable=False),
    sa.Column('department_id', sa.String(length=50), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('used_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['budget_pool_id'], ['budget_pools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department_budgets')
    op.drop_table('budget_ledger')
    op.drop_table('budget_pools')
    # ### end Alembic commands ###