"""add_ecard_design

Revision ID: 3a4043bbb0a6
Revises: f912cc625248
Create Date: 2026-01-26 08:12:41.147601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a4043bbb0a6'
down_revision = 'f912cc625248'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recognitions', sa.Column('ecard_design', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recognitions', 'ecard_design')
    # ### end Alembic commands ###
